public enum PerformPanelType
{
    [EnumMark("整形输入")]
    InputInt,
    [EnumMark("浮点数输入")]
    InputFloat,
    [EnumMark("枚举下拉")]
    DropDownEnum,
    [EnumMark("工具旋转")]
    Vector3ToolRot,
    [EnumMark("零件旋转")]
    Vector3PartRot,
    [EnumMark("零件位置")]
    Vector3PartPos,
    [EnumMark("Vector3")]
    Vector3,
    [EnumMark("Vector2")]
    Vector2,
    [EnumMark("颜色面板")]
    Color,
    [EnumMark("Bool型")]
    Bool,
    [EnumMark("图片视频配置")]
    ImageVideo,
    [EnumMark("字符串输入")]
    String,
    [EnumMark("选择特效")]
    ChoiceSpecialEfficacy,
    [EnumMark("选择屏幕")]
    ChoiceScreen,
    [EnumMark("序列帧图片")]
    Flash,
    [EnumMark("选择材质")]
    ChoiceMaterial,
    [EnumMark("理论试题列表")]
    TheoryList,
    [EnumMark("选择Cid")]
    JKT_String,
    [EnumMark("选择状态")]
    JKT_StateEnum,
    [EnumMark("拆卸与安装")]
    JKT_Movement,
    [EnumMark("通用运动")]
    CommonMotion,
    [EnumMark("模型节点拖拽框")]
    TrsPathString,
    [EnumMark("屏幕点击")]
    ScreenTouch
}